name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use API Key
        env:
          KURAL_API_KEY: ${{ secrets.API_KEY }}
        run: echo "Using API Key: $KURAL_API_KEY"
